services:
  ib-gateway-live:
    image: ghcr.io/gnzsnz/ib-gateway:stable
    container_name: ib-gateway-live
    restart: always
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TWOFA_DEVICE: ""
      TRADING_MODE: live
      READ_ONLY_API: "no"
      TWS_ACCEPT_INCOMING: accept
      TWOFA_TIMEOUT_ACTION: "exit"
      TIME_ZONE: Etc/UTC
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD}
      SAVE_TWS_SETTINGS: "yes"
    ports:
      - "127.0.0.1:4001:4003"
      - "127.0.0.1:6080:6080"
